### ISSUE TITLE
Expanded configuration documentation

### ISSUE THREAD

**Issue by nbuk213** [rnilssoncx/homebridge-pico#1]
Would you be able to provide additional context around the example json.  Getting context errors around server variables, platform setting also appears to be ignored.

**Comment by rnilssoncx** [comment]
Can you share your config.json (just blank out any private data)?

**Comment by nbuk213** [comment]
Hey - really appreciate you taking the time and reaching back out, This
plugin aims to solve what I feel is a glaring hole in Lutron's ecosystem.
And as for me, while very much in the tech industry, developer languages
and XML have never been my focus expertise.

Below is what my config looked like prior to installing the Pico plugin -
(really excited to leverage single/double/long press) I tried to remove the
pre-existing config and just copy/paste the template config and replace
bridge config settings but even after doing that and saving the config -
Homebridge failed to load and I had to re-install on my Raspberry Pi.

 I was getting invalid config around server variables and the "silent"
modifier was being ignored

{
    "bridge": {
        "name": "Rasberry-Pi Bridge",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": XXXXX,
        "pin": "XXX-XX-XXX"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "HomeKit Bridge",
            "port": XXXX,
            "auth": "form",
            "theme": "dark-mode",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "bridgeConnection": {
                "host": "XX.X.X.XXX"
            },
            "accessories": [
                {
                    "name": "Media Keypad",
                    "type": "PJ2-4B",
                    "integrationID": 5
                },
                {
                    "name": "Media Keypad",
                    "type": "PJ2-2B",
                    "integrationID": 8
                },
                {
                    "name": "Bedside Keypad",
                    "type": "PJ2-4B",
                    "integrationID": 9
                }
            ],
            "platform": "LutronCasetaPlatform"
        }
    ]
}

The red callouts in the example - were also called out as invald (bridge
was not as i used my info) Host and port were still invalid as well after
placing the info in.
[image: image.png]

Thanks!!!

**Comment by rnilssoncx** [comment]
You're having this issue because you're not following my configuration instructions.  You're using the instructions for the plugin "LutronCasetaPlatform".  This plugin is called "Pico".  Instructions are here:  https://github.com/rnilssoncx/homebridge-pico

**Comment by nbuk213** [comment]
Apologies, should have been more explicit - I had attached my current
plugin for reference but even when I deleted it out and copy/pasted the
sample config file it came back invalid and crashed the homebridge service.

The below is a screenshot as it's the only way to show the errors, for
"host" "port" "switches".

Hopefully this will give a better picture.

[image: image.png]

Editable copy:
{
    "bridge": {
        "name": "Rasberry-Pi Bridge",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": XXXXX,
        "pin": "XXX-XX-XXX"
    },
    "accessories": [],
    "platforms": [
        {
        "name": "HomeKit Bridge",
        "port": XXXX,
        "auth": "form",
        "theme": "dark-mode",
        "tempUnits": "f",
        "lang": "auto",
        "platform": "Pico",
        "quiet": false,
        "servers": [
                "host": "XX.X.X.XXX",
                "port": 23,
                "switches": [
                    {
                        "name": "Kitchen Pico",
                        "pico": 22,
                        "type": "simple"
                    },
                    {
                        "name": "Home Theater Pico",
                        "pico": [
                            11,
                            31
                        ],
                        "type": "scene"
                    }
                ]

        }
    ]
}

**Comment by nareshkkannan** [comment]
Looks like a missing ] ?  Like where you have the blank line (4th from end)?

**Comment by rnilssoncx** [comment]
The format was wrong for platforms.  The platform for Pico is right now correct in what I put below.

{
    "bridge": {
        "name": "Rasberry-Pi Bridge",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": XXXXX,
        "pin": "XXX-XX-XXX"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "HomeKit Bridge",
            "port": XXXX,
            "auth": "form",
            "theme": "dark-mode",
            "tempUnits": "f",
            "lang": "auto"
        },
        {
            "platform": "Pico",
            "quiet": false,
            "servers": [
            	{
                    "host": "XX.X.X.XXX",
                    "port": 23,
                    "switches": [
                        {
                            "name": "Kitchen Pico",
                            "pico": 22,
                            "type": "simple"
                        },
                        {
                            "name": "Home Theater Pico",
                            "pico": [
                                11,
                                31
                            ],
                            "type": "scene"
                        }
                    ]
                }
            ]
        }
    ]
}

**Comment by nbuk213** [comment]
I believe there are the correct number of brackets - I will completely
wipe my homebridge and start anew, so everything is perfectly aligned and
im only using your example- but given your own example shows the same red
squiggly context errors same as mine this will still be an issue. I shared
the screen grab to convey where the errors were located.

------------------------------
*From:* nareshkkannan <notifications@github.com>
*Sent:* Thursday, July 2, 2020 12:00:57 PM
*To:* rnilssoncx/homebridge-pico <homebridge-pico@noreply.github.com>
*Cc:* nbuk213 <nburk213@gmail.com>; Author <author@noreply.github.com>
*Subject:* Re: [rnilssoncx/homebridge-pico] Expanded configuration
documentation (#1)


Looks like a missing ] ? Like where you have the blank line (4th from end)?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rnilssoncx/homebridge-pico/issues/1#issuecomment-653121141>,
or unsubscribe

**Comment by nbuk213** [comment]
Just wanted to follow-up, this is a carbon copy of the example config on
the github readme then posted within a new new homebridge instance. There
are JSON compatibility issues out of the gate. Not sure how its working
within your environment but something is amiss.

[image: image.png]

**Comment by rnilssoncx** [comment]
There is a problem with my sample - a missing set of braces. 

The servers section is a list, but the example is missing ls the {} around the individual server entry. What I pasted above in this chat is correct.  I’ll fix the doc later today.

**Comment by nbuk213** [comment]
Awesome! Thank you for your time and assistance. Its a real game changer to have the Picos fully compatible with the rest of Lutron’s offerings

________________________________

**Comment by rnilssoncx** [comment]
I've corrected the sample config.  Let me know when you're up and running so we can close this out.

**Comment by nbuk213** [comment]
the servers section is still invalid at same location according to
jsonlint.com. And if there was an update to the example I can not say for
certain if it was propagated. Github does not indicate whether the readme
page has been updated like the repository.

I was able to make a change and get the JSON to validate a bit ago but
while this now appears correct the system fails to initialize - Error logs
at bottom.

Changes in green
"servers": *{*
"host": "11.1.1.111",
"port": 23
},

-----------------------------------------------------
location of JSON failure per JSONLint:
    "servers": [
                "host": "11.1.1.111",
                "port": 23,
                "switches": [



Error: Parse error on line 21:
...rvers": [				"host": "11.1.1.111",				
----------------------^
----Expecting 'EOF', '}', ',', ']', got ':'

-----------------------------------------------------
Error log on home bridge boot after validated JSON config - I would assume
likely due to config not being in expected format

[Pico] Pico Plugin Loaded - Version 0.0.1
[7/4/2020, 3:19:10 PM] TypeError: config.servers is not iterable
    at new Pico (/usr/lib/node_modules/homebridge-pico/index.js:33:31)
    at /usr/lib/node_modules/homebridge/src/server.ts:397:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms
(/usr/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous>
(/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js
(internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
[7/4/2020, 3:19:10 PM] Got SIGTERM, shutting down Homebridge...

**Comment by rnilssoncx** [comment]
The section below is missing braces.  I corrected this in the readme, earlier today.

```
"servers": [
                "host": "11.1.1.111",
                "port": 23,
                "switches": [

Should be:

"servers": [
        {
                "host": "11.1.1.111",
                "port": 23,
                "switches": [
                    ...
                ]
        }
]
```

**Comment by nbuk213** [comment]
Alright, happy to report that it is working 100%. Love that you have the
buttons populate in the correct order as well.

Thanks!

**Comment by rnilssoncx** [comment]
Great news. I’ll close this out.
