### ISSUE TITLE
How does this differ from homebridge-lutron-caseta-smockle?

### ISSUE THREAD

**Issue by ryanschmidt** [rnilssoncx/homebridge-pico#12]
Thanks for the plugin. I'll be trying it asap but I'm curious as to how this compares or relates to the now deprecated [homebridge-lutron-caseta-smockle](https://www.npmjs.com/package/homebridge-lutron-caseta-smockle). I ask because my Picos seem to fail every couple of weeks and require a homebridge restart. I haven't been able to figure out why this is happening so I've been looking for a replacement for the Picos... and then I found this. Just curious if you found an issue with the smockle plugin and decided to make a better solution.

**Comment by rnilssoncx** [comment]
I was not familiar with the plugin you reference, but I have been running and maintaining this one for several years with no issues.

**Comment by ryanschmidt** [comment]
Awesome! No idea how I missed this one when searching for a solution. Thank you.

**Comment by rnilssoncx** [comment]
Let me know what you think!

From a quick look at the code, my plugin has broader pico support and I believe a much more robust connection to the hub. I did a lot of testing to make sure it would recover from any type of issue.

Really, there's not much to go wrong as long as it keeps the connection to the Pro Bridge. 😀

Good luck!

**Comment by ryanschmidt** [comment]
This is very nice to hear. I went to a few very dark places trying to replace Picos with something that still looked nice :)

**Comment by rnilssoncx** [comment]
Sorry for yet another message, but I'd say you should be very happy.  My plugin fully enabled double and long press, which I use quite extensively.  My wife absolutely loves the overloading of the buttons.

I reached out to suggest the smockle put a link to my plugin in his archived one as his is no longer maintained.

**Comment by ryanschmidt** [comment]
Good call on the link on the smockle plugin page. I think it's still used quite a bit but multiple press and long press never seemed to work so I didn't bother.

Being able to support that would make my wife (and kids) happy as well. Looking forward to trying that.

**Comment by jvic1234** [comment]
This plugin is night and day better compared to caseta smockle. I also used tgst plugin before discovering this plugin. What a great plugin. 

Donated for continued support. 

Thank you.
