### ISSUE TITLE
HOOBS Compatiblilty

### ISSUE THREAD

**Issue by MacularDegenerate** [rnilssoncx/homebridge-pico#20]
Is this plugin compatible with HOOBS? As soon as I install this plugin my bridge goes offline.

**Comment by rnilssoncx** [comment]
I do not use hoobs and have never tested with their system. I see there's a docker image for hoobs, so when I get a chance I'll do some testing and see if I can determine why there might be problems. 

If you can post the log it would help as well.

**Comment by MacularDegenerate** [comment]
Just wanted to follow up and say that I was able to get this running with HOOBS. I just had some minor syntax issues with the setup. Thanks for supporting this plugin.
