### ISSUE TITLE
Can this support lutron caseta dimmer switches too?

### ISSUE THREAD

**Issue by lilyball** [rnilssoncx/homebridge-pico#21]
I really want to be able to associate additional actions with my lutron caseta dimmer switches. In particular, I want to be able to make "lights off" on a dimmer switch turn off other lights too (but turning it off with HomeKit shouldn't do this). This plugin README only indicates support for pico remotes. Can this be extended to trigger actions with the dimmers themselves?

**Comment by lilyball** [comment]
I would go ahead and just check bus logging to see if events for this are sent, but I don't have a Pro bridge yet (no point in buying it until I know I can do what I want).

**Comment by rnilssoncx** [comment]
Unfortunately the data on the bus is the same whether you press the switch or the lights are controlled by HomeKit.

**Comment by lilyball** [comment]
So the bus doesn't say "dimmer switch button pressed", instead it says "light at N%"? That's disappointing.

**Comment by rnilssoncx** [comment]
I'd recommend using a long press or double press for this.  That also mean you have control from the switch to operate normally or turn off all the lights.  My wife (who was hard to sell on home automation) really likes this.

Single presses of the kitchen light just turn on and off the main kitchen light (lutron handles this).  Double press also turns on the undercabinet lights.  Long press the kitchen table.  The opposite is also true.

It's a bit different than your vision, but your type of use case is why I made sure to include the overloading.
