### ISSUE TITLE
HomeKit 'Convert To Shortcut' actions no longer working

### ISSUE THREAD

**Issue by MacularDegenerate** [rnilssoncx/homebridge-pico#23]
I recently installed this plugin with HOOBS running on a Raspberry Pi. Things were going great for a while. Recently however, any actions that I assigned to a Pico button (single press, double press, long press - does't matter) as a HomeKit Shortcut (located at the bottom under Advanced when selecting scenes or actions to assign to the button press) stopped working. I had set up some simple automations to dim the lights up/down in intervals based on their current brightness at the time of the button press. These automations still work within the iOS Apple Home app when I press 'Test This Action' and the button presses seem to be showing up in the HOOBS/Hombebridge log, but the action assigned to these button presses are not running. I changed one of the button press sequences that I was having issues with to a non-Shortcut action and it worked fine. Changed it back to a Shortcut automation and the action would not fire. Any suggestions?

**Comment by MacularDegenerate** [comment]
I will also say that the Pico tile within the Apple Home app animates when the button is pressed even thought the configured Shortcut does not run. This seems to suggest that HomeKit recognizes the button was pressed... Maybe a new bug with the Apple Home app? I was running iOS 14.5 general public release when this first started. I tried updating to iOS 14.7 public beta to see if that would help but no such luck :(

**Comment by ShaunRoberts543** [comment]
I am having the same problem.  Was working just fine with Convert To Shortcut actions, now it will only work with direct actions.  It shows appropriate button press in log as well as HomeKit.  I double checked the listed remote to make sure the 3BRL was correct, and it is.  I did not make any changes, it just stopped working.  It is true from multiple remotes as well, not just a single issue.

**Comment by MacularDegenerate** [comment]
Try updating/rebooting any HomeKit hubs you may have like an Apple TV or Home Pod. Rebooting my Apple TV finally did the trick for me.

**Comment by ShaunRoberts543** [comment]
I think that might of worked.  I have 8 HomePod Minis in my house and 4 Apple TVs.  I just disabled the Apple TVs as they are not necessary with all the HomePods.  I reset everything and I tried a couple and they seem to work, but my system is updating with all the HomePods being reset so it will be awhile while I wait for everything to come back onboard.


Thank You!

Shaun

**Comment by rnilssoncx** [comment]
I also find that if you do have AppleTVs active they need to be the 4K version to be reliable.

**Comment by MacularDegenerate** [comment]
I only have a single Apple TV HD. Haven’t had further issues since resetting.

Andrew Polk
________________________________

**Comment by rnilssoncx** [comment]
Closing this issue as everything was working.
