### ISSUE TITLE
Is it possible to expose the dimmers for double and long press?

### ISSUE THREAD

**Issue by lacedup** [rnilssoncx/homebridge-pico#25]
Is it possible to expose the dimmers for double and long press? Thank you

**Comment by rnilssoncx** [comment]
Dimmers send out messages about the dim state, but nothing about button presses.  So there's no way to add the Pico functionality.

**Comment by lacedup** [comment]
Do you think it could be made to turn on to a certain brightness? As is, it’s always 100%

**Comment by rnilssoncx** [comment]
I'd recommend doing that with a scene.
