### ISSUE TITLE
Need Pico models added please!

### ISSUE THREAD

**Issue by mikelong120** [rnilssoncx/homebridge-pico#29]
Hello I jumped the gun and bought a couple of pico remotes before checking to see if they were on the supported list. I’d really appreciate adding these models: 

PJ2-4B-GWH-P02
PJ2-4B-GWH-P03

thanks!

**Comment by rnilssoncx** [comment]
I'm about to add the ability to add custom picos. I'll have the release out this weekend.

**Comment by mikelong120** [comment]
Outstanding! Look forward to tinkering with it.  Thanks for the fast response.

**Comment by mikelong120** [comment]
Just checking in to see if custom Pico ability is still coming. Thanks!

**Comment by WJKramer** [comment]
Any update on this?

**Comment by rnilssoncx** [comment]
I'll have the updated version out this weekend.

**Comment by rnilssoncx** [comment]
The new version is up at v1.1.1-beta.0.  You can pull this version from the Config UI by telling it you want an older version.  Please let me know if you have any issues.  I'll formally publish in a few days if there aren't any problems.

**Comment by dcosson** [comment]
I believe I also have the PJ2-4B-GWH-P03 and just got it set up, turns out it's the same 3 scenes + off configuration as PJ2-4B-XXX-L31 so you don't need to use a custom setting.

**Comment by rnilssoncx** [comment]
Thanks!  The release with custom setting will be out in a couple hours.
