### ISSUE TITLE
AirPlay 2 speakers audio control

### ISSUE THREAD

**Issue by shyawnkarim** [rnilssoncx/homebridge-pico#32]
Before I replace my standard bridge with a pro bridge, will this plug-in allow me to control AirPlay 2 speakers with an audio Pico Remote?

**Comment by rnilssoncx** [comment]
This homebridge module exposes Pico remotes as buttons in HomeKit.  So, if you can build a scene in HomeKit to perform the action, this will work.

If you want to control something like HomePod, you can Play, Pause, etc.  However, I don't believe you can do incremental volume changes.  Maybe something else out there can do this through Homebridge.

Bottom line, this just creates a button event, the rest of the work is handled in HomeKit.

What I've done for their Fan pico is create a series of HomeKit Automations that are based on current state - up his pressed and fan it off, turn fan on to low.  Up is pressed and fan is on low, set fan to Medium, etc.
