### ISSUE TITLE
Unresponsive button presses after period of inactivity

### ISSUE THREAD

**Issue by sethlong1** [rnilssoncx/homebridge-pico#33]
Since install a few months ago, I’ve noticed that button presses on my Pico often need to be repeated several times before HomeKit responds. Once it begins responding (wakes up?), it usually behaves normally. 

This doesn’t seem like it would be typical behavior. 

I’m running homebridge 1.3.8on an RPi 4 Model B/4GB, node v14.18.1, homebridge-pico version 1.0.2 and using the PJ2-3BRL remote. I recently set the plugin as a child bridge, as a way of troubleshooting the issue, but it had no impact.

**Comment by rnilssoncx** [comment]
If you are seeing the presses in the homebridge log then Thr messages are being sent to HomeKit. This kind of issue is almost always related to the HomeKit hub having issues. Sometimes a restart will improve things. 

Using an older appletv or iPad is guaranteed to be problematic.

**Comment by rnilssoncx** [comment]
Closing this issue.
