### ISSUE TITLE
Using pk2-4b-XXX-p04 switch

### ISSUE THREAD

**Issue by riedelcastro** [rnilssoncx/homebridge-pico#37]
Hi,

First, thanks for this amazing plugin! 

My issue is the following I have a pk2-4b-tbl-p04 switch:

https://www.tradesparky.com/lamps-and-lighting/control-gear/lutron/lutron-pk2-4b-tbl-p04-ra2-pico-uni-blk

Which "type" should I use? I tried a few of the PB4-XXX ones (including L01, L41...) but somehow button presses aren't reaching homekit on these. Note that I have a few other PICOs that I already control with this plugin and there are no problems. I am pretty sure I found the right ID in the "Lutron Integration Report" (as I have with the other buttons). 

What could I be doing wrong?

**Comment by rnilssoncx** [comment]
You need to turn on logging and see what ids the buttons produce. The beta version will allow you to define your own pick based on the buttons from the log. 

I'll have a new release this week, but the beta is stable.

**Comment by riedelcastro** [comment]
Never mind, found it: it's the L31.

**Comment by riedelcastro** [comment]
But thanks for the super fast reply!
