### ISSUE TITLE
Support for RA2 Select hub

### ISSUE THREAD

**Issue by cbarratt** [rnilssoncx/homebridge-pico#39]
Hey,

I don't believe in the UK we can get the Lutron Caseta Pro bridge, and I'm shortly about to buy into the RA2 select system. I was wondering if there's even the slimmest possibility this may work? Or if some one has attempted it before, thanks

**Comment by rnilssoncx** [comment]
The RA2 Select hub does not appear to provide the full telnet interface present with the Caseta Pro bridge or the higher end solutions.  It looks like this would not work from my quick good search.
