### ISSUE TITLE
Homeworks

### ISSUE THREAD

**Issue by kikolobo** [rnilssoncx/homebridge-pico#4]
Hello,

Do you know if this code will work with homeworks processor from lutron?

I know the bridge pro does work with it but has a limit of 99 devices and was wondering if this could help eliminate that limit.

**Comment by rnilssoncx** [comment]
Lutron has one protocol, so I don't know why this wouldn't work.  My only question would be around the login - is it the same user/pass and does it have the same nuances.

The current Lutron Pro bridge supports 75 devices, and the plugin is designed to work with multiple Lutron Pro's.  That may be dramatically more cost effective.
