### ISSUE TITLE
Support for PD-5NE ?

### ISSUE THREAD

**Issue by natcl** [rnilssoncx/homebridge-pico#40]
Does this plugin support the favourite button of the PD-5NE ?
I seem to be able to get the state via telnet so I assume it could work ?

Thanks !

**Comment by rnilssoncx** [comment]
That likely will not work.  The favorite button, and all buttons, on an actual switch send out data on the level of things, not presses.  So a favorite press would send out the light level.  Pico switches send out button presses.
