### ISSUE TITLE
single/double presses no longer work after latest update

### ISSUE THREAD

**Issue by rfiorentino1** [rnilssoncx/homebridge-pico#42]
After the 1.2.1 update, I can only use repeated buttons, single/double presses no longer appear in the log/trigger automation. In the log, it says "lost data" for device 3, 4, etc. If I revert to the previous version, everything is perfect again.
Also, the repeat issue seems to be with the on/off buttons only. The other buttons work fine, and never create a loop. Interesting; wondering if Lutron is somehow interfering with this, because you can hold at least the top button to re-pair a remote, etc?

**Comment by rnilssoncx** [comment]
Small typo broke all "normal" functionality.  All should be fixed now in v1.2.2.
