### ISSUE TITLE
Problem typeerror: config.servers is not iterable

### ISSUE THREAD

**Issue by ryanjdesalvo** [rnilssoncx/homebridge-pico#46]
5/14/2022, 12:59:17 AMPico BridgeLoaded plugin 'homebridge-pico'
5/14/2022, 12:59:17 AMPico BridgeLoading 1 platforms...
5/14/2022, 12:59:17 AMPico BridgePicoPico Plugin Loaded - Version 1.2.2
5/14/2022, 12:59:17 AMPico BridgePicoBus Logging set to off
5/14/2022, 12:59:17 AMPico BridgeWARNINGunhandled rejection: TypeError: config.servers is not iterable

**Comment by rnilssoncx** [comment]
Duplicate of issue 45.
