### ISSUE TITLE
Updating button keeps old config

### ISSUE THREAD

**Issue by hmangnx** [rnilssoncx/homebridge-pico#47]
When I go into the pico config inside the home app and update a button setting, aka change it to something else, it doesn’t take the change and keeps the old one no matter what I do. Aka button 1 was turn on kitchen light, but I change it to turn on bedroom light. It will still control the kitchen light.

**Comment by rnilssoncx** [comment]
This plugin only exposes the pico and sends the button presses. It doesn't have anything to do with the actions taken in HomeKit. 

You may have associated the pico with your kitchen light switch in the Lutron app, which is wh6 it continues to control the kitchen light. 

Outside that, it would be something setup in HomeKit itself.
