### ISSUE TITLE
5 button pico mapping (fan)

### ISSUE THREAD

**Issue by jaredzimmerman** [rnilssoncx/homebridge-pico#54]
When utilizing a 5 button "fan" pico the top, bottom, and favorite button make sense to me, but is it possible to get the native for the up and down buttons "increase by X" (e.g. 25%→50%→100%) when controlling a fan?

**Comment by rnilssoncx** [comment]
Unfortunately this plugin only send the button presses.  The way I solved that is to use Shortcuts to handle the logic in the Home app.
