### ISSUE TITLE
Button labels

### ISSUE THREAD

**Issue by llamafilm** [rnilssoncx/homebridge-pico#6]
First, thank you for writing this plugin!  The Pico remotes are so useful and I had several of them otherwise unused.

Would it be possible to label the buttons in HomeKit?  The Homebridge log shows correct names like Off, On, Up, Down, Favorite.  But Apple Home just labels them Button 1, Button 2, etc.  So adding new actions requires some trial and error.

**Comment by rnilssoncx** [comment]
Actually, they are labeled. If you use another app like the Eve app you will see them properly labeled. 

There are a lot of great HomeKit apps out there that allow for a more powerful HomeKit experience. It has many capabilities not exposed in the Home app.

**Comment by llamafilm** [comment]
Okay thanks! Yes you're right it works in Eve.  I'll send feedback to Apple then.
