### ISSUE TITLE
Support for Homebridge Bond

### ISSUE THREAD

**Issue by mdiskin** [rnilssoncx/homebridge-pico#8]
I'm willing to work on and contribute this if it makes sense to this plugin. I'd like to be able to just reference the homebridge light and fan accessory and have the pico for ceiling fan able to work without the traditional button programming. Could see other receipes for Sonos or dimmer lights been a great timesaver.

**Comment by oripaamoni** [comment]
I would simply like to donate! This plugin has made my setup so much cleaner and has been rock solid so far.

**Comment by rnilssoncx** [comment]
Regarding the light and fan, I'm not sure how you could do that. You have to actually control the light and fan with the plugin which I'm not sure is possible. 

If you figure this out and get it working, then I'd be glad to incorporate. 

What I did is just set up the buttons based on conditions to provide normal function. I use the app "Control" which makes this easy. It's a little work, but does the job.
