### ISSUE TITLE
Feature request: better switch naming

### ISSUE THREAD

**Issue by rwgunther** [rnilssoncx/homebridge-pico#9]
When configuring the plug-in, you can assign names to each switch. But when the accessories get created in Homebridge and HomeKit, the service names are generic, e.g., on, up, favorite, down, off. Renaming each of these manually is tedious, and if you don't do it, it's confusing when you see multiple services with the same name. Any way you could incorporate the switch name into the service name so they could ultimately end up looking something like this without a lot of redundant renaming?

![Screen Shot 2020-11-26 at 13 03 05](https://user-images.githubusercontent.com/68545697/100381816-cf7da180-2fe7-11eb-9739-d717392dbacd.png)

Unrelated: This is my absolute favorite plug-in. I specifically purchased a Pro bridge just for this, and I've talked about it on my podcasts. If you threw a Sponsor button on Github or a Donate link in Homebridge, I absolutely would!

**Comment by rnilssoncx** [comment]
Thanks for the great feedback!  I'm glad you like the plugin - it's essential to my home automation as well.

What app are you using?  In the apps I use - Home, Eve, Controller, etc. the Pico remote is listed with it's name, and then inside you have the labels for configuration of the various buttons.  The Home apps is the worst as it doesn't show the labels.

This is definitely possible - but since it wasn't part of the original concept I need to see how much of a change is needed.

**Comment by rwgunther** [comment]
The first (and worst) place where I see this is in Homebridge itself. Every new switch adds another collection of buttons like this:

![Screen Shot 2020-11-27 at 14 49 42](https://user-images.githubusercontent.com/68545697/101068516-d0be4980-3566-11eb-858a-c510d1ff50af.png)

I also use (and highly recommend) the Controller app for scene/automation management. It gives deep visibility into nearly every attribute of every HomeKit object. It's outstanding for building precise scenes and automations. Here's how it exposes the services you've created for a Pico accessory, so I think it comes down to perhaps concatenating the accessory and service name for more descriptive services since that's what some apps expose:

![IMG_6889A23B163B-1](https://user-images.githubusercontent.com/68545697/101069966-b6856b00-3568-11eb-8e74-ba49aa5315ee.jpeg)

And then, yes, Home. I realize you don't have any control over managing those.

**Comment by rnilssoncx** [comment]
Thanks - I use controller as well.  I find the representation in all apps (outside the home app) to be correct. Go into a pico remote and the buttons are clearly labeled. 

The homebridge GUI does show as you shared, but it's not correct - they don't really support the buttons last I checked. 

I think it would be a relatively simple change to put in a setting to do the name concatenation.  I'll look at that and some log changes in the next few weeks.

**Comment by rnilssoncx** [comment]
This capability has been added with the `longtime` setting in v1.0.0.  It's off by default as it only seems relevant when you look at the Accessories in the Homebridge UI.  Ideally the Homebridge UI will properly represent buttons in the future.

The plugin is also now verified and I setup donations.
